# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-14 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('id', models.CharField(blank=True, max_length=9, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cityid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityid', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cityid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('time', models.DateTimeField()),
                ('username', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=20)),
                ('class_time', models.CharField(max_length=20)),
                ('class_address', models.CharField(max_length=20)),
                ('class_field', models.CharField(db_column='class', max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=1)),
                ('notice', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('time', models.DateTimeField()),
                ('count_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('class_field', models.CharField(db_column='class', max_length=10)),
                ('class_name', models.CharField(max_length=20)),
                ('class_time', models.CharField(max_length=20)),
                ('class_address', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=1)),
                ('username', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('ip', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('count_id', models.CharField(max_length=10)),
                ('timediff', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'count_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('username', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'discuss',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fileall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('class_field', models.CharField(db_column='class', max_length=20)),
                ('filename', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'fileall',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Homework01',
            fields=[
                ('time', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('score', models.CharField(max_length=10)),
                ('notice', models.CharField(max_length=300)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'homework01',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Homework07',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('id1', models.IntegerField()),
                ('id2', models.IntegerField()),
                ('ans', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'homework07',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Homework1',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('class_field', models.CharField(db_column='class', max_length=20)),
                ('input', models.CharField(max_length=200)),
                ('print_field', models.CharField(db_column='print', max_length=100)),
                ('detail', models.CharField(max_length=200)),
                ('lang', models.CharField(max_length=1)),
                ('chapter', models.CharField(max_length=2)),
                ('id2', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'homework1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Homework2',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('class_field', models.CharField(db_column='class', max_length=10)),
                ('detail', models.CharField(max_length=2000)),
                ('ans', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'homework2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Homework7',
            fields=[
                ('time', models.DateTimeField()),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('chapter', models.CharField(max_length=2)),
                ('title', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'homework7',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Homework71',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.CharField(max_length=4)),
                ('id2', models.IntegerField()),
                ('chapter', models.CharField(max_length=2)),
                ('question', models.CharField(max_length=800)),
                ('ans', models.CharField(max_length=200)),
                ('jx', models.CharField(max_length=800)),
                ('notice', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'homework71',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Identify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=20)),
                ('openid', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=40)),
                ('dormitory', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'identify',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Info1',
            fields=[
                ('number', models.CharField(blank=True, max_length=8, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('grade', models.CharField(blank=True, max_length=4, null=True)),
                ('academy', models.CharField(blank=True, max_length=4, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('qq', models.CharField(blank=True, max_length=11, null=True)),
                ('id', models.CharField(blank=True, max_length=18, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'info1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=10)),
                ('count', models.IntegerField()),
                ('notice', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'lab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('content', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=10)),
                ('receiver', models.CharField(max_length=100)),
                ('class_field', models.CharField(db_column='class', max_length=10)),
                ('type', models.CharField(max_length=1)),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('title', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'navigation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('time', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=1)),
                ('lang', models.CharField(max_length=1)),
                ('chapter', models.CharField(max_length=2)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=800)),
                ('code', models.CharField(max_length=1000)),
                ('jx', models.CharField(max_length=12000)),
                ('input', models.CharField(max_length=100)),
                ('print_field', models.CharField(db_column='print', max_length=100)),
                ('username', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramAns',
            fields=[
                ('time', models.DateTimeField()),
                ('username', models.CharField(max_length=20)),
                ('score', models.CharField(max_length=10)),
                ('notice', models.CharField(max_length=300)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'program_ans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramAssign',
            fields=[
                ('time', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_field', models.CharField(db_column='class', max_length=10)),
                ('username', models.CharField(max_length=20)),
                ('id2', models.IntegerField()),
            ],
            options={
                'db_table': 'program_assign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=128, unique=True)),
                ('atime', models.DateTimeField()),
                ('data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('username', models.CharField(max_length=20)),
                ('class_field', models.CharField(db_column='class', max_length=20)),
                ('openid', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'signin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'software',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('major', models.CharField(blank=True, max_length=20, null=True)),
                ('class_field', models.CharField(db_column='class', max_length=5)),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('score3', models.IntegerField()),
                ('class2', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('notice', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tmp1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('id1', models.IntegerField()),
                ('count', models.BigIntegerField()),
                ('sum', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True)),
                ('avg', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'tmp1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tmp2016',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('major', models.CharField(blank=True, max_length=20, null=True)),
                ('sum_score', models.FloatField(blank=True, null=True)),
                ('score1', models.DecimalField(blank=True, decimal_places=0, max_digits=54, null=True)),
                ('score2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tmp2016',
                'managed': False,
            },
        ),
    ]
